# Generated by Django 4.1.2 on 2022-10-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_persona_contrasena_alter_persona_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fechaNacimiento',
            field=models.DateTimeField(verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='primerApellido',
            field=models.CharField(max_length=50, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='primerNombre',
            field=models.CharField(max_length=50, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='segundoApellido',
            field=models.CharField(max_length=50, verbose_name='Segundo Nombre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='segundoNombre',
            field=models.CharField(max_length=50, verbose_name='Segundo Nombre'),
        ),
    ]
