# Generated by Django 4.1.2 on 2022-10-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_persona_fechanacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fechaNacimiento',
            field=models.DateField(verbose_name='Fecha Nacimiento'),
        ),
    ]
