# Generated by Django 4.1.2 on 2022-10-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_persona_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(max_length=50, verbose_name='Correo'),
        ),
    ]
