# Generated by Django 4.1.2 on 2022-10-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_persona_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fechaNacimiento',
        ),
    ]
