# Generated by Django 4.1.2 on 2022-10-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_remove_persona_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fechaNacimiento',
            field=models.DateField(null=True, verbose_name='Fecha Nacimiento'),
        ),
    ]
