# Generated by Django 4.1.2 on 2022-10-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_alter_persona_fechanacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fechaNacimiento',
        ),
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.PositiveIntegerField(default=0, max_length=3, verbose_name='Edad'),
        ),
    ]
