# Generated by Django 4.1.2 on 2022-10-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_remove_persona_fechanacimiento_persona_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.PositiveIntegerField(default=0, verbose_name='Edad'),
        ),
    ]
