# Generated by Django 4.1.2 on 2022-10-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_alter_persona_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
    ]
